Add a new chef_infra alias to the chef_zero provisioner (Recreating PR 1730)
test-kitchen/test-kitchen pull request #1771
Opened 2021-06-26 15:42 UTC by i5pranay93

# Description

We are renaming provisioner chef_zero to chef_infra and making it backward compatible,  also replacing chef_infra as the default provisioner from chef_solo.

## Issues Resolved

fixes https://github.com/test-kitchen/test-kitchen/issues/1708
fixes https://github.com/test-kitchen/test-kitchen/issues/1723
Recreating- https://github.com/test-kitchen/test-kitchen/pull/1730

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

2021-06-28 13:41 UTC, marcparadise commented on lib/kitchen/provisioner/chef_infra.rb
> +# Copyright (C) 2013, Fletcher Nichol
We should add an additional copyright line here, `Copyright (C) Chef Software Inc.`

2021-06-28 13:43 UTC, marcparadise requested changes
This looks good to me, thanks for re-working this to clear up the history issues.  There are two minor corrections inline, after which I think this is good to go.

2021-06-28 13:43 UTC, marcparadise commented on spec/kitchen/provisioner_spec.rb
> +      provisioner = Kitchen::Provisioner.for_plugin("chef_zero", {})
Description and plugin don't match - it says 'chef_infra' is given but we're giving 'chef_zero'.

2021-06-28 15:55 UTC, marcparadise commented
There also seems to be somethin ghappening with the history here. Maybe we could  pair up tomorrow morning (EDT) to resolve?

2021-07-01 09:57 UTC, closed without merging

2021-07-01 09:58 UTC, i5pranay93 commented
Closing due to messed up commit history